In [68]:
import pandas as pd

In [69]:
profiles=pd.read_csv("profiles.csv")

In [70]:
profiles.columns

Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'essay0',
       'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7',
       'essay8', 'essay9', 'ethnicity', 'height', 'income', 'job',
       'last_online', 'location', 'offspring', 'orientation', 'pets',
       'religion', 'sex', 'sign', 'smokes', 'speaks', 'status'],
      dtype='object')

In [98]:
profiles['body_type'].value_counts()

4.0    14652
1.0    12711
2.0    11819
0.0     6843
5.0     6553
3.0     1430
6.0      642
Name: body_type, dtype: int64

In [72]:
len(profiles)

59946

In [73]:
# TRANSFORMS THE "religion" COLUMN

profiles["religion"]= profiles["religion"].str.extract(r"(\b(?:agnosticism|christianity|catholicism|buddhism|other|hinduism|judaism|islam))")

In [74]:
# TRANSFORMS THE "ethnicity" COLUMN

profiles["ethnicity"]= profiles["ethnicity"].str.extract(r"(\b(?:black|hispanic|asian|white))")

In [75]:
# TRANSFORMS THE "offspring" COLUMN

profiles["offspring"]=profiles["offspring"].replace({
    'doesn&rsquo;t want kids': 0,
    'doesn&rsquo;t have kids, and doesn&rsquo;t want any': 0,

    'doesn&rsquo;t have kids': 0,

    'doesn&rsquo;t have kids, but might want them':0, 
    'might want kids': 0,

    'doesn&rsquo;t have kids, but wants them':0,
    'wants kids': 0,

    'has a kid, but doesn&rsquo;t want more': 1,

    'has a kid' : 1,

    'has a kid, and might want more': 1,

    'has a kid, and wants more': 1,

    'has kids, but doesn&rsquo;t want more': 2,

    'has kids': 2,

    'has kids, and might want more': 2,

    'has kids, and wants more': 2
})

In [76]:
# TRANSFORMS THE "body_type" COLUMN

profiles["body_type"]=profiles["body_type"].replace({
    'skinny': 0,
    'thin': 0,
    'used up': 0,
    'fit': 1,
    'athletic': 2,
    'jacked': 3,
    'full figured': 3,
    'average': 4,
    'curvy': 5,
    'a little extra': 5,
    'overweight': 6,
    'rather not say': 6
    
})

In [77]:
# TRANSFORMS THE "drinks" COLUMN

profiles["drinks"]=profiles["drinks"].replace({
    'not at all': 0,
    'rarely': 1,
    'socially': 2,
    'often': 3,
    'very often': 4,
    'desperately': 5
})

In [78]:
profiles["orientation"]=profiles["orientation"].replace({
    'not at all': 0,
    'rarely': 1,
    'socially': 2,
    'often': 3,
    'very often': 4,
    'desperately': 5
})

In [79]:
# TRANSFORMS THE "drugs" COLUMN
print(profiles["drugs"].unique())
profiles["drugs"]=profiles["drugs"].replace({
    'never':0,
    'sometimes':1,
    'often':2
})
profiles["drugs"].unique()

['never' 'sometimes' nan 'often']


array([ 0.,  1., nan,  2.])

In [80]:
# TRANSFORMS THE "smokes" COLUMN
print(profiles["smokes"].unique())
profiles["smokes"]=profiles["smokes"].replace({
    'no':0,
    'trying to quit':1,
    'sometimes':2,
    'when drinking': 3,
    'yes':4
})
profiles["smokes"].unique()

['sometimes' 'no' nan 'when drinking' 'yes' 'trying to quit']


array([ 2.,  0., nan,  3.,  4.,  1.])

In [81]:
# TRANSFORMS THE "status" COLUMN
print(profiles["status"].unique())
profiles["status"]=profiles["status"].replace({
    'unknown': -1,
    'single': 0,
    'available': 1,
    'seeing someone': 2,
    'married': 3
})
profiles["status"].unique()

['single' 'available' 'seeing someone' 'married' 'unknown']


array([ 0,  1,  2,  3, -1], dtype=int64)

In [82]:
# SPLIT THE "pets" COLUMN INTO "pets_dogs" AND "pets_cats"


profiles["pets_dogs"]= profiles["pets"].str.extract(r"(\b(?:likes|has|dislikes)\s+dogs\b)")
profiles["pets_cats"]= profiles["pets"].str.extract(r"(\b(?:likes|has|dislikes)\s+cats\b)")
        
profiles["pets"].isna().sum()

# TRANSFORMS THE "pets_dogs" AND "pets_cats" COLUMN

# "pets_dogs"
profiles["pets_dogs"]=profiles["pets_dogs"].replace({"dislikes dogs": 0, "has dogs": 1, "likes dogs": 2})

profiles["pets_dogs"]=profiles["pets_dogs"].fillna(-1)

# "pets_cats"

profiles["pets_cats"]=profiles["pets_cats"].replace({"dislikes cats": 0, "has cats": 1, "likes cats": 2})

profiles["pets_cats"]=profiles["pets_cats"].fillna(-1)
                   

In [83]:
# TRANSFORMS THE "sign" COLUMN


profiles["sign"]=profiles["sign"].str.extract(r"(gemini|cancer|pisces|aquarius|taurus|virgo|sagittarius|cancer|leo|scorpio|libro|capricorn)")

profiles["sign"]=profiles["sign"].replace({
    'capricorn': 0,
    'aquarius': 1,
    'pisces': 2,
    'aries': 3,
    'taurus': 4,
    'gemini': 5,
    'cancer': 6,
    'leo': 7,
    'virgo': 8,
    'libro': 9,
    'scorpio': 10,
    'sagittarius': 11
})

profiles["sign"].value_counts()

7.0     4374
5.0     4310
6.0     4206
8.0     4141
4.0     4140
10.0    4134
2.0     3946
11.0    3942
1.0     3928
0.0     3573
Name: sign, dtype: int64

In [92]:
# SPECIFIC MODEL DATA TRANSFORMATION

training_column=["age","drinks","drugs","smokes","diet"]

target_column=["body_type"]
model_data=profiles[training_column+target_column]
print(len(model_data))
#ONE HOT ENCODING ON "education", "job"

model_data=pd.get_dummies(model_data,columns=["diet"])

#DROPPING NA VALUES

model_data=model_data.dropna()

model_data.info()

59946
<class 'pandas.core.frame.DataFrame'>
Int64Index: 39427 entries, 0 to 59944
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       39427 non-null  int64  
 1   drinks                    39427 non-null  float64
 2   drugs                     39427 non-null  float64
 3   smokes                    39427 non-null  float64
 4   body_type                 39427 non-null  float64
 5   diet_anything             39427 non-null  uint8  
 6   diet_halal                39427 non-null  uint8  
 7   diet_kosher               39427 non-null  uint8  
 8   diet_mostly anything      39427 non-null  uint8  
 9   diet_mostly halal         39427 non-null  uint8  
 10  diet_mostly kosher        39427 non-null  uint8  
 11  diet_mostly other         39427 non-null  uint8  
 12  diet_mostly vegan         39427 non-null  uint8  
 13  diet_mostly vegetarian    39427 non-null  uint8  
 14  

In [94]:
import torch
from torch import nn
from torch import optim
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [95]:
target_feature=model_data[target_column]
training_features=model_data.drop(target_column, axis=1)



training_features=torch.tensor(training_features.values, dtype=torch.float)
target_feature=torch.tensor(model_data[target_column].values, dtype=torch.long).view(-1)

X_train, X_test, y_train, y_test=train_test_split(training_features, target_feature, test_size=0.2, random_state=42)

target_feature

tensor([5, 4, 2,  ..., 1, 4, 2])

In [96]:
# NEURAL NETWORK

offspring_model=nn.Sequential(
    nn.Linear(22,80),
    nn.ReLU(),
    nn.Linear(80,40),
    nn.ReLU(),
    nn.Linear(40,7)
)


loss=nn.CrossEntropyLoss()
optimizer=optim.Adam(offspring_model.parameters(), lr=0.01)


num_epochs= 3000

for epoch in range(num_epochs):
    predictions=offspring_model(X_train)
    BCE=loss(predictions,y_train)
    BCE.backward()
    optimizer.step()
    optimizer.zero_grad()
    if (epoch+1) % 100 ==0:
        predicted_labels = torch.argmax(predictions, dim=1)
        accuracy=accuracy_score(predicted_labels, y_train)
        print(f"{epoch+1}/{num_epochs} - Accuracy: {accuracy.item():.4f} Loss: {BCE.item():.4f}")

100/3000 - Accuracy: 0.2811 Loss: 1.6770
200/3000 - Accuracy: 0.2871 Loss: 1.6679
300/3000 - Accuracy: 0.2866 Loss: 1.6656
400/3000 - Accuracy: 0.2868 Loss: 1.6649
500/3000 - Accuracy: 0.2879 Loss: 1.6624
600/3000 - Accuracy: 0.2878 Loss: 1.6621
700/3000 - Accuracy: 0.2895 Loss: 1.6603
800/3000 - Accuracy: 0.2884 Loss: 1.6601
900/3000 - Accuracy: 0.2902 Loss: 1.6590
1000/3000 - Accuracy: 0.2898 Loss: 1.6594
1100/3000 - Accuracy: 0.2892 Loss: 1.6585
1200/3000 - Accuracy: 0.2886 Loss: 1.6598
1300/3000 - Accuracy: 0.2894 Loss: 1.6569
1400/3000 - Accuracy: 0.2887 Loss: 1.6564
1500/3000 - Accuracy: 0.2883 Loss: 1.6562
1600/3000 - Accuracy: 0.2887 Loss: 1.6564
1700/3000 - Accuracy: 0.2878 Loss: 1.6564
1800/3000 - Accuracy: 0.2892 Loss: 1.6547
1900/3000 - Accuracy: 0.2886 Loss: 1.6556
2000/3000 - Accuracy: 0.2891 Loss: 1.6547
2100/3000 - Accuracy: 0.2901 Loss: 1.6545
2200/3000 - Accuracy: 0.2905 Loss: 1.6534
2300/3000 - Accuracy: 0.2897 Loss: 1.6535
2400/3000 - Accuracy: 0.2897 Loss: 1.6544
2

In [99]:
offspring_model.eval()
with torch.no_grad():
    ## YOUR SOLUTION HERE ##
    predictions = offspring_model(X_test)
    predicted_labels = torch.argmax(predictions, dim=1)
    accuracy = accuracy_score(y_test, predicted_labels) 
    report = classification_report(y_test,predicted_labels)
    print(report)

              precision    recall  f1-score   support

           0       0.19      0.04      0.06       945
           1       0.27      0.21      0.24      1751
           2       0.27      0.12      0.16      1698
           3       0.00      0.00      0.00       222
           4       0.29      0.73      0.41      2210
           5       0.09      0.01      0.01       959
           6       0.00      0.00      0.00       101

    accuracy                           0.28      7886
   macro avg       0.16      0.16      0.13      7886
weighted avg       0.23      0.28      0.21      7886



C:\Users\Eric\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Eric\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Eric\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [103]:
# DECISION TREES



from sklearn.tree import DecisionTreeClassifier


target_feature=model_data[target_column]
training_features=model_data.drop(target_column, axis=1)


X_train, X_test, y_train, y_test=train_test_split(training_features, target_feature, test_size=0.2, random_state=42)


classifier = DecisionTreeClassifier(random_state = 0, max_depth=11)
classifier.fit(X_train, y_train)

print(classifier.score(X_test, y_test))

0.279229013441542
